config/routes.rb
Kotelok::Application.routes.draw do

  get "gallery/index"

  devise_for :users

  root to: 'boilers#index'

  resources :boilers, only: [:index]
  resources :spares, only: [:index]
  resources :documentations, only: [:index, :show]
  resources :prices, only: [:index, :show]
  namespace :admin do
    resources :boilers, except: :show
    resources :spares, except: :show
    resources :documentations, except: :show
    resources :prices, except: :show
    resources :gimages, except: [:edit, :update]
  end

  mount Ckeditor::Engine => '/ckeditor'

end

app/models/boiler.rb
class Boiler < ActiveRecord::Base
  attr_accessible :title, :power, :amount_of_space, :price, :preview, :body
end

app/models/ckeditor/asset.rb
class Ckeditor::Asset < ActiveRecord::Base
  include Ckeditor::Orm::ActiveRecord::AssetBase
  include Ckeditor::Backend::Paperclip
end

app/models/ckeditor/picture.rb
class Ckeditor::Picture < Ckeditor::Asset
  has_attached_file :data,
                    :url  => "/ckeditor_assets/pictures/:id/:style_:basename.:extension",
                    :path => ":rails_root/public/ckeditor_assets/pictures/:id/:style_:basename.:extension",
                    :styles => { :content => '800>', :thumb => '118x100#' }

  validates_attachment_size :data, :less_than => 2.megabytes
  validates_attachment_presence :data

  def url_content
    url(:content)
  end
end

app/models/documentation.rb
class Documentation < ActiveRecord::Base
  attr_accessible :title, :body
end

app/models/gimage.rb
class Gimage < ActiveRecord::Base
  attr_accessible :file
  has_attached_file :file,
                    :styles => { original: "1000x1000>", thumb: "200x200>" },
                    :default_url => "/assets/logo.png"
  validates :file, :attachment_presence => true
end

app/models/price_page.rb
class PricePage < ActiveRecord::Base
  attr_accessible :body
end

app/models/spare.rb
class Spare < ActiveRecord::Base
  attr_accessible :title, :price, :preview, :body
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :trackable, :validatable,
         :token_authenticatable
  attr_accessible :email, :password, :remember_me, :password_confirmation, :phone, :address
end

app/controllers/admin/prices_controller.rb
# coding: utf-8

class Admin::PricesController < ApplicationController

  def index
    @prices_page = PricePage.first
    if @prices_page
      redirect_to edit_admin_price_path @prices_page
    end
  end

  def show
    @prices_page = PricePage.find(params[:id])
  end

  def new
    @prices_page = PricePage.new
  end

  def edit
    @prices_page = PricePage.find(params[:id])
  end

  def create
    @prices_page = PricePage.new(params[:price_page])

    respond_to do |format|
      if @prices_page.save
        format.html { redirect_to prices_path, notice: 'Страница цен успешно создана.' }
      else
        format.html { render action: "new" }
      end
    end
  end

  def update
    @prices_page = PricePage.find(params[:id])

    respond_to do |format|
      if @prices_page.update_attributes(params[:price_page])
        format.html { redirect_to prices_path, notice: 'Страница цен успешно обновлена.' }
      else
        format.html { render action: "edit" }
      end
    end
  end

  def destroy
    @prices_page = PricePage.find(params[:id])
    @prices_page.destroy

    respond_to do |format|
      format.html { redirect_to admin_prices_url }
      format.json { head :no_content }
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/boilers_controller.rb
class BoilersController < ApplicationController
  before_filter :tab

  def index
    params[:page] ||= 1
    params[:per_page] ||= 7
    @boilers = Boiler.paginate page: params[:page], per_page: params[:per_page]
  end

  def show
    @boiler = Boiler.find(params[:id])
  end

  private

  def tab
    @tab = 'boilers'
  end
end

app/controllers/documentations_controller.rb
class DocumentationsController < ApplicationController
  before_filter :tab

  def index
    params[:page] ||= 1
    params[:per_page] ||= 7
    @documentations = Documentation.paginate page: params[:page], per_page: params[:per_page]
  end

  def show
    @documentation = Documentation.find(params[:id])
  end

  private

  def tab
    @tab = 'docs'
  end
end

app/controllers/gallery_controller.rb
class GalleryController < ApplicationController
  before_filter :tab

  def index
    @images = Gimage.all
  end

  private

  def tab
    @tab = 'gallery'
  end
end

app/controllers/prices_controller.rb
class PricesController < ApplicationController
  before_filter :tab

  def index
  end

  def show
    @price_page = PricePage.find(params[:id])
  end

  private

  def tab
    @tab = 'price'
  end
end

app/controllers/spares_controller.rb
class SparesController < ApplicationController
  before_filter :tab

  def index
    params[:page] ||= 1
    params[:per_page] ||= 7
    @spares = Spare.paginate page: params[:page], per_page: params[:per_page]
  end

  def show
    @spare = Spare.find(params[:id])
  end

  private

  def tab
    @tab = 'spares'
  end
end

app/helpers/admin/admin_helper.rb
module Admin::AdminHelper
end

app/helpers/admin/prices_helper.rb
module Admin::PricesHelper
end

app/helpers/admin/spares_helper.rb
module Admin::SparesHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
  def admin
    User.first
  end

  def boiler_page
    Boiler.first
  end

  def spare_page
    Spare.first
  end

  def documentation_page
    Documentation.first
  end

  def price_page
    PricePage.first
  end

  def meta_keywords(tags = nil)
    if tags.present?
      content_for :meta_keywords, tags
    else
      content_for?(:meta_keywords) ? content_for(:meta_keywords) : ''
    end
  end

  def meta_description(desc = nil)
    if desc.present?
      content_for :meta_description, desc
    else
      content_for?(:meta_description) ? content_for(:meta_description) : ''
    end
  end

end

app/helpers/boilers_helper.rb
module BoilersHelper
end

app/helpers/documentations_helper.rb
module DocumentationsHelper
end

app/helpers/gallery_helper.rb
module GalleryHelper
end

app/helpers/prices_helper.rb
module PricesHelper
end

app/helpers/spares_helper.rb
module SparesHelper
end

app/views/admin/prices/_form.haml
- if @prices_page.errors.any?
  - @prices_page.errors.full_messages.each do |msg|
    .alert.alert-error
      %button.close{type: :button, 'data-dismiss' => 'alert'}
      = msg
= form_for(@prices_page, url: @prices_page.id ? admin_price_path(@prices_page) : admin_prices_path, method: @prices_page.id ? :put : :post) do |f|
  .field
    %br
    = f.cktext_area :body, :ckeditor => {:language => "ru"}

  .actions.text-center
    %br
    = f.submit 'Сохранить изменения', class: 'btn btn-success'
= content_for :assets do
  = javascript_include_tag 'ckeditor/init'

app/views/admin/prices/edit.html.erb
<h1>Редактировать страницу цен</h1>

<%= render 'form' %>

app/views/admin/prices/index.haml
- unless price_page
  = link_to 'Создать страницу цен', new_admin_price_path, class: 'btn btn-success'

-#
-#= link_to 'New Spare', new_admin_spare_path, class: 'btn btn-success'
-#
-#.grid
-#  = grid(@spares_grid, upper_pagination_panel: true) do |g|
-#    - g.blank_slate content_tag(:div, 'No records found')
-#    - g.column name: 'Title', attribute: 'title'
-#    - g.column name: 'Price', attribute: 'price'
-#    - g.column do |spare|
-#      - link_to('Show', spare, class: 'btn btn-mini')
-#    - g.column do |spare|
-#      - link_to('Edit', edit_admin_spare_path(spare), class: 'btn btn-mini btn-info')
-#    - g.column do |spare|
-#      - link_to('Destroy', [:admin, spare], method: :delete, class: 'btn btn-mini btn-danger', data: { confirm: 'Are you sure?' })

app/views/admin/prices/new.html.erb
<h1>Создать страницу цен</h1>

<%= render 'form' %>

app/views/prices/index.haml
= content_for :title, "Купить твердотопливный котел, пиролизные котлы, цена"
- meta_description "В нашем интернет-магазине Вы сможете купить твердотопливный котел двух видов: с нагнетающим вентилятором и с оттягивающим. Цена, описание, гарантия и доставка пиролизных котлов."
- meta_keywords "Купить твердотопливный котел"
- if price_page
  = raw price_page.body