config/routes.rb
Kotelok::Application.routes.draw do

  get "gallery/index"

  devise_for :users

  root to: 'boilers#index'

  resources :boilers, only: [:index]
  resources :spares, only: [:index]
  resources :documentations, only: [:index, :show]
  resources :prices, only: [:index, :show]
  namespace :admin do
    resources :boilers, except: :show
    resources :spares, except: :show
    resources :documentations, except: :show
    resources :prices, except: :show
    resources :gimages, except: [:edit, :update]
  end

  mount Ckeditor::Engine => '/ckeditor'

end

app/models/boiler.rb
class Boiler < ActiveRecord::Base
  attr_accessible :title, :power, :amount_of_space, :price, :preview, :body
end

app/models/ckeditor/asset.rb
class Ckeditor::Asset < ActiveRecord::Base
  include Ckeditor::Orm::ActiveRecord::AssetBase
  include Ckeditor::Backend::Paperclip
end

app/models/ckeditor/picture.rb
class Ckeditor::Picture < Ckeditor::Asset
  has_attached_file :data,
                    :url  => "/ckeditor_assets/pictures/:id/:style_:basename.:extension",
                    :path => ":rails_root/public/ckeditor_assets/pictures/:id/:style_:basename.:extension",
                    :styles => { :content => '800>', :thumb => '118x100#' }

  validates_attachment_size :data, :less_than => 2.megabytes
  validates_attachment_presence :data

  def url_content
    url(:content)
  end
end

app/models/documentation.rb
class Documentation < ActiveRecord::Base
  attr_accessible :title, :body
end

app/models/gimage.rb
class Gimage < ActiveRecord::Base
  attr_accessible :file
  has_attached_file :file,
                    :styles => { original: "1000x1000>", thumb: "200x200>" },
                    :default_url => "/assets/logo.png"
  validates :file, :attachment_presence => true
end

app/models/price_page.rb
class PricePage < ActiveRecord::Base
  attr_accessible :body
end

app/models/spare.rb
class Spare < ActiveRecord::Base
  attr_accessible :title, :price, :preview, :body
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :trackable, :validatable,
         :token_authenticatable
  attr_accessible :email, :password, :remember_me, :password_confirmation, :phone, :address
end

app/controllers/admin/gimages_controller.rb
# coding: utf-8

class Admin::GimagesController < ApplicationController

  def index
    @gimages = Gimage.all
  end

  def new
    @gimage = Gimage.new
  end

  def create
    @gimage = Gimage.new(params[:gimage])

    if @gimage.save
      redirect_to admin_gimages_path, notice: 'Изображение успешно добавлено в галерею.'
    else
      render action: "new"
    end
  end

  def destroy
    @gimage = Gimage.find(params[:id])
    @gimage.destroy

    redirect_to admin_gimages_url
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/boilers_controller.rb
class BoilersController < ApplicationController
  before_filter :tab

  def index
    params[:page] ||= 1
    params[:per_page] ||= 7
    @boilers = Boiler.paginate page: params[:page], per_page: params[:per_page]
  end

  def show
    @boiler = Boiler.find(params[:id])
  end

  private

  def tab
    @tab = 'boilers'
  end
end

app/controllers/documentations_controller.rb
class DocumentationsController < ApplicationController
  before_filter :tab

  def index
    params[:page] ||= 1
    params[:per_page] ||= 7
    @documentations = Documentation.paginate page: params[:page], per_page: params[:per_page]
  end

  def show
    @documentation = Documentation.find(params[:id])
  end

  private

  def tab
    @tab = 'docs'
  end
end

app/controllers/gallery_controller.rb
class GalleryController < ApplicationController
  before_filter :tab

  def index
    @images = Gimage.all
  end

  private

  def tab
    @tab = 'gallery'
  end
end

app/controllers/prices_controller.rb
class PricesController < ApplicationController
  before_filter :tab

  def index
  end

  def show
    @price_page = PricePage.find(params[:id])
  end

  private

  def tab
    @tab = 'price'
  end
end

app/controllers/spares_controller.rb
class SparesController < ApplicationController
  before_filter :tab

  def index
    params[:page] ||= 1
    params[:per_page] ||= 7
    @spares = Spare.paginate page: params[:page], per_page: params[:per_page]
  end

  def show
    @spare = Spare.find(params[:id])
  end

  private

  def tab
    @tab = 'spares'
  end
end

app/helpers/admin/admin_helper.rb
module Admin::AdminHelper
end

app/helpers/admin/gimages_helper.rb
module Admin::GimagesHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
  def admin
    User.first
  end

  def boiler_page
    Boiler.first
  end

  def spare_page
    Spare.first
  end

  def documentation_page
    Documentation.first
  end

  def price_page
    PricePage.first
  end

  def meta_keywords(tags = nil)
    if tags.present?
      content_for :meta_keywords, tags
    else
      content_for?(:meta_keywords) ? content_for(:meta_keywords) : ''
    end
  end

  def meta_description(desc = nil)
    if desc.present?
      content_for :meta_description, desc
    else
      content_for?(:meta_description) ? content_for(:meta_description) : ''
    end
  end

end

app/helpers/boilers_helper.rb
module BoilersHelper
end

app/helpers/documentations_helper.rb
module DocumentationsHelper
end

app/helpers/gallery_helper.rb
module GalleryHelper
end

app/helpers/prices_helper.rb
module PricesHelper
end

app/helpers/spares_helper.rb
module SparesHelper
end

app/views/admin/gimages/_form.haml
- if @gimage.errors.any?
  - @gimage.errors.full_messages.each do |msg|
    .alert.alert-error
      %button.close{type: :button, 'data-dismiss' => 'alert'}
      = msg
= form_for([:admin, @gimage]) do |f|
  .field
    %br
    .fileupload.fileupload-new{'data-provides' => 'fileupload'}
      .fileupload-preview.fileupload-exists.thumbnail{style: 'max-width: 200px; max-height: 150px; line-height: 20px;'}
        = image_tag @gimage.file.url, style: 'max-width: 200px; max-height: 150px;'
      %div
        = f.file_field :file

  .actions.text-center
    %br
    = f.submit 'Сохранить изменения', class: 'btn btn-success'

app/views/admin/gimages/index.haml
= javascript_include_tag 'lightbox/js/lightbox-2.6.min.js'
= stylesheet_link_tag 'lightbox/css/lightbox.css'

= link_to 'Добавить изображение', new_admin_gimage_path, class: 'btn btn-success'
%br
%br
%table.table.table-striped
  %thead
    %tr
      %th
        Изображение
      %th
  %tbody
    - @gimages.each do |image|
      %tr
        %td
          - link_to(image_tag(image.file.url(:thumb), style: 'height: 150px', class: 'img-polaroid'), image.file.url(:original), 'data-lightbox' => "roadtrip")
        %td
          - link_to('Удалить', [:admin, image], method: :delete, class: 'btn btn-mini btn-danger', data: { confirm: 'Are you sure?' })

app/views/admin/gimages/new.html.erb
<h1>Добавить изображение в галерею</h1>

<%= render 'form' %>